In [11]:
import pandas as pd
import random
import math

In [12]:
books = pd.read_csv('orginal_df_books.csv', on_bad_lines='skip')
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

# 1 Dosotosowanie dazy danych do naszych potrzeb

## 1.1 Usuwanie zbędnych kolumn

In [13]:
colums_to_delete = {"isbn", "isbn13", "text_reviews_count"}
for column_name in colums_to_delete:
    books.drop(column_name, inplace=True, axis=1)

In [14]:
books

,bookID,title,authors,average_rating,language_code,num_pages,ratings_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,eng,652,2095690,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,eng,870,2153167,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,eng,352,6333,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,eng,435,2339585,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,eng,2690,41428,9/13/2004,Scholastic
...,...,...,...,...,...,...,...,...,...
11118,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,eng,512,156,12/21/2004,Da Capo Press
11119,45633,You Bright and Risen Angels,William T. Vollmann,4.08,eng,635,783,12/1/1988,Penguin Books
11120,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,eng,415,820,8/1/1993,Penguin Books
11121,45639,Poor People,William T. Vollmann,3.72,eng,434,769,2/27/2007,Ecco
11122,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,spa,272,113,5/28/2006,Edimat Libros

## 1.2 Dodawanie kolumn

In [15]:
def Make_List_From_txt(title: str):
    genres = open('additional_data_base_info/' + title + '.txt','r')
    genres_list =[]
    for line in genres:
        genres_list.append(line.strip())
    return genres_list
    
def Create_Extra_Column(column_name: str, min: int, max: int, content_list: list, seed: int = 0):
    random.seed(seed)
    rows_number = books.shape[0]+1
    new_column = []
    for id in range(1,rows_number):
        element_number = random.randint(min, max)
        row_content = random.choices(content_list,k = element_number)
        if min == 1 and max == 1:
            new_column.append(row_content[0])
        else:
            new_column.append(row_content)
    books[column_name] = new_column

In [16]:
genres = Make_List_From_txt("genres")
target_groups = Make_List_From_txt("target_groups")
tags = Make_List_From_txt("tags")
countrys = Make_List_From_txt("country_of_origin")

Create_Extra_Column("Genres", 1, 3, genres)
Create_Extra_Column("target_groups", 1, 1, target_groups)
Create_Extra_Column("tags", 1, 7, tags)
Create_Extra_Column("country_of_origin", 1, 1, countrys)


# liczba wyporzyczeń w miesiącu
random.seed(0)
books['month_rentals'] = (books["ratings_count"] / random.randint(10,15)).astype(int)

books.head()

,bookID,title,authors,average_rating,language_code,num_pages,ratings_count,publication_date,publisher,Genres,target_groups,tags,country_of_origin,month_rentals
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,eng,652,2095690,9/16/2006,Scholastic Inc.,"[travel, magical_realism]",single_mothers,"[mafia, egyptian_mythology, angels, superhero,...",France,161206
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,eng,870,2153167,9/1/2004,Scholastic Inc.,"[parenting_and_families, short_story]",young_adults,"[gore, egyptian_mythology, love_triangle, guns]",Poland,165628
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,eng,352,6333,11/1/2003,Scholastic,"[parenting_and_families, contemporary_fiction]",boys,"[time_travel, gambling]",Mexico,487
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,eng,435,2339585,5/1/2004,Scholastic Inc.,[young_adult],introverts,"[time_travel, violence, slice_of_life]",Korea,179968
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,eng,2690,41428,9/13/2004,Scholastic,"[horror, action_adventure]",engaged_people,"[egyptian_mythology, isekai, gods, egyptian_my...",Russia,3186

## 1.3 zmiana kolejności kolumn oraz nazw kolumn

In [17]:
books = books[["bookID", "title", "authors", "publisher", "Genres", "target_groups", "tags", "  num_pages", "language_code", "country_of_origin", "publication_date", "average_rating", "ratings_count", "month_rentals"]]

# zmiana nazwy
books.rename(columns = {'ratings_count':'ratings_count', '  num_pages':'num_pages'}, inplace = True)



books.head()

,bookID,title,authors,publisher,Genres,target_groups,tags,num_pages,language_code,country_of_origin,publication_date,average_rating,ratings_count,month_rentals
0,0,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,Scholastic Inc.,"[travel, magical_realism]",single_mothers,"[mafia, egyptian_mythology, angels, superhero,...",652,eng,France,9/16/2006,4.57,2095690,161206
1,1,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,Scholastic Inc.,"[parenting_and_families, short_story]",young_adults,"[gore, egyptian_mythology, love_triangle, guns]",870,eng,Poland,9/1/2004,4.49,2153167,165628
2,2,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,Scholastic,"[parenting_and_families, contemporary_fiction]",boys,"[time_travel, gambling]",352,eng,Mexico,11/1/2003,4.42,6333,487
3,3,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,Scholastic Inc.,[young_adult],introverts,"[time_travel, violence, slice_of_life]",435,eng,Korea,5/1/2004,4.56,2339585,179968
4,4,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,Scholastic,"[horror, action_adventure]",engaged_people,"[egyptian_mythology, isekai, gods, egyptian_my...",2690,eng,Russia,9/13/2004,4.78,41428,3186

## 1.4 Zmiana zawartości kolumn

In [ ]:
books["bookID"] = range(0, books.count()[0])

# Zapis danych

In [18]:
books.to_csv("books.csv", index = False)